### ISSUE TITLE
feat: a way to know if WS is going to retry connecting

### ISSUE THREAD

**Issue by aytunch** [felangel/web_socket_client#10]
**Description**

Right now we get `Disconnected` from the `.connection` stream of WS.
But there is no way if the WS will try to reconnect afterwards or if it exhausted retrying.

**Additional Context**

I am creating a client API. While using a `await for` in `ws.connection`, I want to return if we are successfully connected or not.
If we get `Connected` I return true.
But if i get the first `Disconnected`, I should not return false since maybe the WS under the hood will try to connect again.

You can expose a bool getter called `willRetry` which can solve this ambiguity.

Or if there is something I am missing please do tell :)

```
      await for (ConnectionState event in _ws!.connection) {
        if (event is Connected) {
          return true;
        }
        if (event is Disconnected) {  // (&& _ws!.willRetry == false)
          return false; //maybe it will try connecting again?
        }
      }
```

**Comment by Switernal** [comment]
Maybe you can add a listener to connection like this: 

```dart
socket.connection.listen((state) {
    if (state is Reconnecting) {
      ...
    }
  });
```

and now you can know if WS's state has changed.
