### ISSUE TITLE
feat: Reconnecting state close code

### ISSUE THREAD

**Issue by artemsorochan** [felangel/web_socket_client#50]
**Description**

Hello, is it possible to receive the close code, once the connection state is "Reconnecting"?

Giving the context, we are passing user's auth token to header when trying to connect to the web-socket. In case the token is invalid, back-end closes connection with specific error code, which mobile should recognize and regenerate the token. 

So is it possible to intercept the close code between reconnection attempts by web_socket_client?

**Comment by felangel** [comment]
You should be able to save the close code from the last disconnected state.

Closing for now but if my suggestion doesn't help let me know and I'm happy to continue the conversation 👍
