### ISSUE TITLE
docs: Dart Native

### ISSUE THREAD

**Issue by dickermoshe** [felangel/web_socket_client#58]
**Description**

Does this package work on iOS...
Doesnt seem like it should, being that `package:web` only works on Web, but:

<img width="435" alt="image" src="https://github.com/felangel/web_socket_client/assets/75931499/bc5cd6de-6696-4f0f-b54e-81bf103a8fd8">

**Comment by felangel** [comment]
Hi @dickermoshe 👋 
The package should work on all platforms 👍
